### ISSUE TITLE
Unable to upload NoMethodError

### ISSUE THREAD

**Issue by highcup** [e621ng/e621ng#237]
With a fresh install of e621 I am unable to upload png, jpeg, or gif files. The bug seems to have been introduced in commit 015b81203a67ca5eded499cf0de4766b7b12ef6e

Error
```error: NoMethodError - undefined method `duration=' for #<Post:0x00007f23704f0f48> Did you mean? rating=```

Backtrace
```/home/danbooru/.gem/ruby/2.7.0/gems/activemodel-6.0.3.3/lib/active_model/attribute_methods.rb:432:in `method_missing'
/vagrant/app/logical/upload_service.rb:74:in `block in convert_to_post'
/vagrant/app/logical/upload_service.rb:58:in `tap'
/vagrant/app/logical/upload_service.rb:58:in `convert_to_post'
/vagrant/app/logical/upload_service.rb:41:in `create_post_from_upload'
/vagrant/app/logical/upload_service.rb:26:in `start!'
/vagrant/app/controllers/uploads_controller.rb:37:in `create'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'
/home/danbooru/.gem/ruby/2.7.0/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rakismet-1.5.4/lib/rakismet/middleware.rb:10:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:567:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:37:in `call_app'
/home/danbooru/.gem/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/danbooru/.gem/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/ssl.rb:80:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
/home/danbooru/.gem/ruby/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/home/danbooru/.rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/home/danbooru/.rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/home/danbooru/.rubies/ruby-2.7.0/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'```

**Comment by kiranoot** [comment]
This is one of a few inconsistencies between the live database and the migrations that I need to resolve. The live DB was migrated with different fields and one of them was a numeric field named `duration` within the posts table. You can add it manually for now until I work it into a copy of the database schema for the dev machine.

At some point I need to sit down and yank all of the old migrations out of the repo, as they don't work, can't work, etc. And resolve the remaining differences between the live DB and the dev machine DB. I've had a bad habit of migrating live changes into the dev DB manually because adding them as migrations would be technically incorrect and cause fun issues when deploying the code to the production servers.
